import type { SupabaseClient } from "@supabase/supabase-js";
import { money, round2 } from "@/lib/accounting/money";

export interface JournalLineInput {
  accountId: string;
  debit?: number;
  credit?: number;
  description?: string;
}

export interface PostJournalEntryInput {
  tenantId: string;
  date: string; // YYYY-MM-DD
  narration: string;
  lines: JournalLineInput[];
  referenceType?: string;
  referenceId?: string;
  isAutoGenerated?: boolean;
  createdBy?: string | null;
}

export class UnbalancedJournalError extends Error {
  constructor(totalDebit: number, totalCredit: number) {
    super(`Journal entry does not balance: debit ${totalDebit} !== credit ${totalCredit}`);
    this.name = "UnbalancedJournalError";
  }
}

/**
 * Posts a double-entry journal entry. Throws UnbalancedJournalError if
 * debits and credits don't match — this is the single source of truth for
 * "is this entry structurally valid", checked before hitting the DB
 * constraint (which would also reject it, but this gives a clearer error).
 */
export async function postJournalEntry(
  supabase: SupabaseClient,
  input: PostJournalEntryInput
) {
  let totalDebit = money(0);
  let totalCredit = money(0);
  for (const line of input.lines) {
    totalDebit = totalDebit.plus(line.debit ?? 0);
    totalCredit = totalCredit.plus(line.credit ?? 0);
  }

  const debitRounded = round2(totalDebit);
  const creditRounded = round2(totalCredit);

  if (debitRounded !== creditRounded) {
    throw new UnbalancedJournalError(debitRounded, creditRounded);
  }

  const entryNumber = await generateEntryNumber(supabase, input.tenantId, input.date);

  const { data: entry, error: entryError } = await supabase
    .from("journal_entries")
    .insert({
      tenant_id: input.tenantId,
      entry_number: entryNumber,
      date: input.date,
      narration: input.narration,
      reference_type: input.referenceType ?? "manual",
      reference_id: input.referenceId ?? null,
      total_debit: debitRounded,
      total_credit: creditRounded,
      is_auto_generated: input.isAutoGenerated ?? false,
      created_by: input.createdBy ?? null,
    })
    .select()
    .single();

  if (entryError) throw entryError;

  const lineRows = input.lines.map((line, idx) => ({
    journal_entry_id: entry.id,
    account_id: line.accountId,
    debit: round2(line.debit ?? 0),
    credit: round2(line.credit ?? 0),
    description: line.description ?? null,
    sort_order: idx,
  }));

  const { error: linesError } = await supabase
    .from("journal_entry_lines")
    .insert(lineRows);

  if (linesError) throw linesError;

  return entry;
}

async function generateEntryNumber(
  supabase: SupabaseClient,
  tenantId: string,
  date: string
): Promise<string> {
  const fy = financialYearLabel(date);
  const { count } = await supabase
    .from("journal_entries")
    .select("id", { count: "exact", head: true })
    .eq("tenant_id", tenantId)
    .like("entry_number", `JE-${fy}-%`);

  const seq = (count ?? 0) + 1;
  return `JE-${fy}-${String(seq).padStart(5, "0")}`;
}

/** Indian financial year label (Apr–Mar), e.g. 2026-03-15 -> "2025-26" */
export function financialYearLabel(dateStr: string, fyStartMonth = 4): string {
  const d = new Date(dateStr);
  const year = d.getFullYear();
  const month = d.getMonth() + 1; // 1-12
  if (month >= fyStartMonth) {
    return `${year}-${String((year + 1) % 100).padStart(2, "0")}`;
  }
  return `${year - 1}-${String(year % 100).padStart(2, "0")}`;
}

/**
 * Reverses a journal entry by posting an equal-and-opposite entry
 * (never deletes original entries — audit trail integrity).
 */
export async function reverseJournalEntry(
  supabase: SupabaseClient,
  tenantId: string,
  originalEntryId: string,
  reason: string,
  createdBy?: string | null
) {
  const { data: original, error } = await supabase
    .from("journal_entries")
    .select("*, journal_entry_lines(*)")
    .eq("id", originalEntryId)
    .single();

  if (error) throw error;

  const reversedLines: JournalLineInput[] = original.journal_entry_lines.map(
    (l: { account_id: string; debit: number; credit: number; description: string | null }) => ({
      accountId: l.account_id,
      debit: l.credit,
      credit: l.debit,
      description: l.description ?? undefined,
    })
  );

  return postJournalEntry(supabase, {
    tenantId,
    date: new Date().toISOString().slice(0, 10),
    narration: `Reversal of ${original.entry_number}: ${reason}`,
    lines: reversedLines,
    referenceType: "reversal",
    referenceId: originalEntryId,
    isAutoGenerated: true,
    createdBy,
  });
}
