import type { SupabaseClient } from "@supabase/supabase-js";
import { postJournalEntry, type JournalLineInput } from "@/lib/accounting/journal";

/**
 * Posts the accounting entry for a finalized (non-draft) sales invoice:
 *   Dr Accounts Receivable         (total_amount)
 *     Cr Sales Income               (taxable_value)
 *     Cr Output CGST                (cgst_amount)
 *     Cr Output SGST                (sgst_amount)
 *     Cr Output IGST                (igst_amount)
 *
 * Credit notes reverse the direction. Requires system accounts to already
 * exist in the chart of accounts (seeded by migration 0003).
 */
export async function postInvoiceToJournal(
  supabase: SupabaseClient,
  tenantId: string,
  invoiceId: string,
  createdBy?: string | null
) {
  const { data: invoice, error: invErr } = await supabase
    .from("invoices")
    .select("*")
    .eq("id", invoiceId)
    .single();
  if (invErr) throw invErr;
  if (invoice.journal_entry_id) return invoice.journal_entry_id; // already posted

  const receivableAccount = await getSystemAccount(supabase, tenantId, "1100");
  const salesAccount = await getSystemAccount(supabase, tenantId, "4000");
  const outputCgst = await getSystemAccount(supabase, tenantId, "2100");
  const outputSgst = await getSystemAccount(supabase, tenantId, "2101");
  const outputIgst = await getSystemAccount(supabase, tenantId, "2102");

  const isCreditNote = invoice.invoice_type === "credit_note";
  const lines: JournalLineInput[] = [];

  if (!isCreditNote) {
    lines.push({
      accountId: receivableAccount.id,
      debit: invoice.total_amount,
      description: `Invoice ${invoice.invoice_number}`,
    });
    if (invoice.taxable_value > 0)
      lines.push({ accountId: salesAccount.id, credit: invoice.taxable_value });
    if (invoice.cgst_amount > 0)
      lines.push({ accountId: outputCgst.id, credit: invoice.cgst_amount });
    if (invoice.sgst_amount > 0)
      lines.push({ accountId: outputSgst.id, credit: invoice.sgst_amount });
    if (invoice.igst_amount > 0)
      lines.push({ accountId: outputIgst.id, credit: invoice.igst_amount });
  } else {
    // Credit note: reverse of a sale
    lines.push({
      accountId: receivableAccount.id,
      credit: invoice.total_amount,
      description: `Credit note ${invoice.invoice_number}`,
    });
    if (invoice.taxable_value > 0)
      lines.push({ accountId: salesAccount.id, debit: invoice.taxable_value });
    if (invoice.cgst_amount > 0)
      lines.push({ accountId: outputCgst.id, debit: invoice.cgst_amount });
    if (invoice.sgst_amount > 0)
      lines.push({ accountId: outputSgst.id, debit: invoice.sgst_amount });
    if (invoice.igst_amount > 0)
      lines.push({ accountId: outputIgst.id, debit: invoice.igst_amount });
  }

  const entry = await postJournalEntry(supabase, {
    tenantId,
    date: invoice.issue_date,
    narration: `${isCreditNote ? "Credit note" : "Sales invoice"} ${invoice.invoice_number}`,
    lines,
    referenceType: "invoice",
    referenceId: invoice.id,
    isAutoGenerated: true,
    createdBy,
  });

  await supabase.from("invoices").update({ journal_entry_id: entry.id }).eq("id", invoice.id);

  return entry.id;
}

/**
 * Posts the accounting entry for an expense:
 *   Dr Expense Category            (taxable_value)
 *   Dr Input CGST/SGST/IGST        (gst amounts, if ITC eligible)
 *     Cr Accounts Payable / Bank / Cash   (amount, less TDS if applicable)
 *     Cr TDS Payable                       (tds_amount, if applicable)
 */
export async function postExpenseToJournal(
  supabase: SupabaseClient,
  tenantId: string,
  expenseId: string,
  createdBy?: string | null
) {
  const { data: expense, error: expErr } = await supabase
    .from("expenses")
    .select("*")
    .eq("id", expenseId)
    .single();
  if (expErr) throw expErr;
  if (expense.journal_entry_id) return expense.journal_entry_id;

  const inputCgst = await getSystemAccount(supabase, tenantId, "1200");
  const inputSgst = await getSystemAccount(supabase, tenantId, "1201");
  const inputIgst = await getSystemAccount(supabase, tenantId, "1202");
  const tdsPayable = await getSystemAccount(supabase, tenantId, "2200");
  const payable = await getSystemAccount(supabase, tenantId, "2000");

  const paymentAccountId = expense.bank_account_id
    ? await getLinkedLedgerAccountId(supabase, expense.bank_account_id)
    : (await getSystemAccount(supabase, tenantId, "1000")).id; // default: cash

  const lines: JournalLineInput[] = [];
  const taxable = expense.taxable_value ?? expense.amount;

  lines.push({
    accountId: expense.category_account_id,
    debit: taxable,
    description: expense.description ?? "Expense",
  });
  if (expense.is_itc_eligible) {
    if (expense.cgst_amount > 0) lines.push({ accountId: inputCgst.id, debit: expense.cgst_amount });
    if (expense.sgst_amount > 0) lines.push({ accountId: inputSgst.id, debit: expense.sgst_amount });
    if (expense.igst_amount > 0) lines.push({ accountId: inputIgst.id, debit: expense.igst_amount });
  }

  const netPayable = expense.amount - (expense.tds_amount ?? 0);
  const settlementAccountId = expense.status === "paid" ? paymentAccountId : payable.id;

  lines.push({ accountId: settlementAccountId, credit: netPayable });
  if (expense.tds_applicable && expense.tds_amount > 0) {
    lines.push({ accountId: tdsPayable.id, credit: expense.tds_amount });
  }

  const entry = await postJournalEntry(supabase, {
    tenantId,
    date: expense.date,
    narration: `Expense: ${expense.description ?? expense.expense_number ?? "Untitled"}`,
    lines,
    referenceType: "expense",
    referenceId: expense.id,
    isAutoGenerated: true,
    createdBy,
  });

  await supabase.from("expenses").update({ journal_entry_id: entry.id }).eq("id", expense.id);

  return entry.id;
}

async function getSystemAccount(supabase: SupabaseClient, tenantId: string, code: string) {
  const { data, error } = await supabase
    .from("accounts")
    .select("id, code")
    .eq("tenant_id", tenantId)
    .eq("code", code)
    .single();
  if (error || !data) {
    throw new Error(
      `System account with code ${code} not found for tenant ${tenantId}. Run the seed migration first.`
    );
  }
  return data;
}

async function getLinkedLedgerAccountId(supabase: SupabaseClient, bankAccountId: string) {
  const { data, error } = await supabase
    .from("bank_accounts")
    .select("account_id")
    .eq("id", bankAccountId)
    .single();
  if (error || !data?.account_id) {
    throw new Error(`Bank account ${bankAccountId} has no linked ledger account.`);
  }
  return data.account_id;
}
